name: HN

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    - uses: FedericoCarboni/setup-ffmpeg@v1
      id: setup-ffmpeg

    - name: Install package
      run: |
        sudo apt-get -y install ffmpeg git nodejs imagemagick wget
        
    - name: Download File Bot
      run: |
        wget https://github.com/AyGemuy/HN/archive/refs/heads/master.zip
        
    - name: Unzip File Bot
      run: |
        unzip master.zip
        
    - name: Run File Bot
      run: |
        cd HN-master && npm install && npm start
