name: HN

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
  - uses: actions/checkout@v2
  - uses: FedericoCarboni/setup-ffmpeg@v1
    id: setup-ffmpeg
  - run: sudo apt-get -y install ffmpeg git nodejs imagemagick wget && wget https://github.com/AyGemuy/HN/archive/refs/heads/master.zip && unzip master.zip && cd HN-master && npm install && npm start
